ebook_metadata:
  title: ༄༅། །ཚིག་བདུན་བླ་མའི་རྣལ་འབྱོར་བྱིན་རླབས་ཆར་འབེབས་ཀྱི་དམིགས་ཁྲིད་ཉུང་བསྡུས་ཟབ་ལམ་བཅུད་དྲིལ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  sku: SHE-DKR-14
  layers:
  - book_title
  - author
  - quotation
  - yigchung
web_metadata:
  title:
    en: The Combined Essences of the Profound Path:A Short Meditation Instruction
      on The Rain of Blessing, the Guru Yoga practice of the Seven-Line Vajra Supplication
    bo: ཚིག་བདུན་བླ་མའི་རྣལ་འབྱོར་བྱིན་རླབས་ཆར་འབེབས་ཀྱི་དམིགས་ཁྲིད་ཉུང་བསྡུས་ཟབ་ལམ་བཅུད་དྲིལ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 14
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༤
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-14
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-14.epub
  description:
    en: ''
    bo: ''
